name: faithflow_islam
description: "FaithFlow ISLAM - Islamic Learning App"
publish_to: 'none'
version: 0.1.0
# version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  # adhan_dart: ^1.0.0
  adhan: ^2.0.0+1
  hijri_date: ^1.0.0  
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"